apiVersion: apps/v1 # for versions of Kubernetes <1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: example-wordpress
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: example
      tier: frontend
      env: prod
  template:
    metadata:
      labels:
        app: example
        tier: frontend
        env: prod
    spec:
      containers:
      - name: wordpress
        image: registry.gitlab.com/USERNAME/PROJECT_NAME/wordpress:v1.0.0
        imagePullPolicy: Always
        env:
        - name: WPVAR_WP_HOME
          valueFrom:
            configMapKeyRef:
              name: example-config
              key: WP_HOME
        - name: WPVAR_WP_SITEURL
          valueFrom:
            configMapKeyRef:
              name: example-config
              key: WP_SITEURL
        - name: WPVAR_TABLE_PREFIX
          valueFrom:
            configMapKeyRef:
              name: example-config
              key: TABLE_PREFIX
        - name: WPVAR_WP_CONTENT_DIR
          valueFrom:
            configMapKeyRef:
              name: example-config
              key: WP_CONTENT_DIR
        - name: WPVAR_FS_METHOD
          valueFrom:
            configMapKeyRef:
              name: example-config
              key: FS_METHOD
        - name: WPVAR_WP_DEBUG
          valueFrom:
            configMapKeyRef:
              name: example-config
              key: WP_DEBUG
        - name: WPVAR_WP_DEBUG_LOG
          valueFrom:
            configMapKeyRef:
              name: example-config
              key: WP_DEBUG_LOG
        - name: WPVAR_WP_DEBUG_DISPLAY
          valueFrom:
            configMapKeyRef:
              name: example-config
              key: WP_DEBUG_DISPLAY
        - name: WPVAR_WP_POST_REVISIONS
          valueFrom:
            configMapKeyRef:
              name: example-config
              key: WP_POST_REVISIONS
        - name: WPVAR_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: example-config
              key: DB_HOST
        - name: WPVAR_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: example-config
              key: DB_NAME
        - name: WPVAR_DB_CHARSET
          valueFrom:
            configMapKeyRef:
              name: example-config
              key: DB_CHARSET
        - name: WPVAR_DB_COLLATE
          valueFrom:
            configMapKeyRef:
              name: example-config
              key: DB_COLLATE
        - name: WPVAR_DB_USER
          valueFrom:
            secretKeyRef:
              name: example-db-secret
              key: DB_USER
        - name: WPVAR_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: example-db-secret
              key: DB_PASSWORD
        - name: WPVAR_AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: example-wp-secret
              key: AUTH_KEY
        - name: WPVAR_SECURE_AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: example-wp-secret
              key: SECURE_AUTH_KEY
        - name: WPVAR_LOGGED_IN_KEY
          valueFrom:
            secretKeyRef:
              name: example-wp-secret
              key: LOGGED_IN_KEY
        - name: WPVAR_NONCE_KEY
          valueFrom:
            secretKeyRef:
              name: example-wp-secret
              key: NONCE_KEY
        - name: WPVAR_AUTH_SALT
          valueFrom:
            secretKeyRef:
              name: example-wp-secret
              key: AUTH_SALT
        - name: WPVAR_SECURE_AUTH_SALT
          valueFrom:
            secretKeyRef:
              name: example-wp-secret
              key: SECURE_AUTH_SALT
        - name: WPVAR_LOGGED_IN_SALT
          valueFrom:
            secretKeyRef:
              name: example-wp-secret
              key: LOGGED_IN_SALT
        - name: WPVAR_NONCE_SALT
          valueFrom:
            secretKeyRef:
              name: example-wp-secret
              key: NONCE_SALT
        - name: VOLUME_MOUNT_PATH
          value: "/var/www/example.com"
        ports:
        - containerPort: 80
          name: wordpress-http
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/example.com
#  UNCOMMENT WHEN TUTORIAL POINTS YOU TO THIS PLACE - Git authorization automation
#        - name: ssh-keys
#          readOnly: true
#          mountPath: /home/deployer/.ssh/secret
      imagePullSecrets:
          - name: registry.gitlab.com
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: example-wordpress-pvc
#  UNCOMMENT WHEN TUTORIAL POINTS YOU TO THIS PLACE - Git authorization automation
#      - name: ssh-keys
#        secret:
#          secretName: gitlab-deploy-key
#          items:
#          - key: config
#            path: config
#            mode: 0644
#          - key: ssh-privatekey
#            path: ssh-privatekey
#            mode: 0644
#          - key: ssh-publickey
#            path: ssh-publickey
#            mode: 0644